name: Update version
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    uses: podmania/actions/.github/workflows/update-version.yml@main
    with:
      package: radarr
      upstream: Radarr/Radarr
      tag-prefix: v
      dep-type: dotnet
